# Nome do workflow
name: CI/CD Pipeline Java com H2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Job 1: Build e Testes
  build-and-test:
    name: Build & Test com Java
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build e Testes com Maven
        run: mvn -B verify

  # Job 2: Build e Push Docker
  build-and-push-docker:
    name: Construir e Publicar Imagem Docker
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Login no GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Construir e enviar a imagem Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest

  # Job 3: Deploy em Staging
  deploy-staging:
    name: Deploy em Homologação
    runs-on: ubuntu-latest
    needs: build-and-push-docker
    environment:
      name: staging
      url: https://staging.gerenciador-tarefas.com
    steps:
      - name: Deploy para ambiente de Staging
        run: |
          echo "Deploy para Staging..."
          # comando real de deploy iria aqui

  # Job 4: Deploy em Produção
  deploy-production:
    name: Deploy em Produção
    runs-on: ubuntu-latest
    needs: deploy-staging
    environment:
      name: production
      url: https://gerenciador-tarefas.com
    steps:
      - name: Deploy para ambiente de Produção
        run: |
          echo "Deploy para Produção..."
          # comando real de deploy iria aqui
